version: "3.3"

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  back-end:
    build: .
    ports:
      - '8888:8888'
    links:
      - mongo
    env_file:
      - 'development.env'
    volumes:
      - ./:/usr/src/app
